name: .Net Core App
on:
  push:
    branches: main
  pull_request:
    branches: main
  #workflow_dispatch:  
env:
  AZURE_WEBAPP_NAME: sample string 6
  AZURE_WEBAPP_PACKAGE_PATH: .
  PATH_TO_SOLUTION: sample string 4
  PATH_TO_PROJ: sample string 5
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: sample string 8
        include-prerelease: true
    - name: Build with dotnet
      run: dotnet build ${{ env.PATH_TO_SOLUTION }}
...
