## Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
## More GitHub Actions for Azure: https://github.com/Azure/actions

name: Custom action workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  SONAR_HOST_URL: 'http://40.87.111.97:8080'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        include-prerelease: false
        
    - name: Build with dotnet
      run: dotnet build MySampleWebApp/MySampleWebApp.sln --configuration Release

    - name: Startup Command
      id: hola
      uses: nisargshah1410/jsactiondemo@v2.9.3
      with:
        language: angular 
        cov: coverlet
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
        sonarqube-required: yes
        
    
    #- name: npm build, and test
     # run: |
      #  npm install --save-dev @angular-devkit/build-angular
       # npm install karma --save-dev
      #  npm install codecov --save-dev
      #  ng test
        
    #- name: Echo Startup Command
    #  run: echo "${{ steps.hola.outputs.startupcmd }}"
    
    #- name: Code Coverage
    #  run: echo "${{ steps.hola.outputs.coveragetest }}"
    
    
   # - name: Coverage if condition
    #  run : | 
    #    ${{ steps.hola.outputs.coveragetest }}
      
    
    
   # - name: installing dependencies
    #  run: |
       # ${{ steps.hola.outputs.startupcmd }}
        
   
   
    
