name: .Net Core App
on:
  push:
    branches: main
  pull_request:
    branches: main
env:
  AZURE_WEBAPP_NAME: dotnetcoresample-1
  AZURE_WEBAPP_PACKAGE_PATH: .
  PATH_TO_SOLUTION: MySampleWebApp/MySampleWebApp.sln
  PATH_TO_PROJ: MySampleWebAppTests1/MySampleWebAppTests1.csproj
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        include-prerelease: true
...
