name: .Net Core App
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch: 
env:
  AZURE_WEBAPP_NAME: 'dotnetcoresample-1' 
  AZURE_WEBAPP_PACKAGE_PATH: .
  PATH_TO_SOLUTION: MySampleWebApp/MySampleWebApp.sln
  PATH_TO_PROJ: MySampleWebAppTests1/MySampleWebAppTests1.csproj
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
    - uses: actions/download-artifact@v2
    - with:
        name: .net-app
    - name: Deploy to Azure Web App
    - id: deploy-to-webapp
    - uses: azure/webapps-deploy@v2
    - with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.DOTNET_WEB_APP }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
...
